spring:
  application:
    name: user-client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scshop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
  thymeleaf:
    cache: false
    encoding: utf-8
    model: HTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://jnick.xyz:8761/eureka/,http://jnick.xyz:8762/eureka/,http://jnick.xyz:8763/eureka/
mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml
  type-aliases-package: com.user.common.usercommon.entity
server:
  port: 9090
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
feign:
  hystrix:
    enabled: true