spring:
  application:
    name: config-server
  boot:
    admin:
      client:
        url: http://jnick.xyz:8761:8084
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/TechLjn/spring-config-repo
          username: 2376571392@qq.com
          password: 6Ljn19970928
  zipkin:
    base-url: http://jnick.xyz:8761:9411
eureka:
  client:
    service-url:
      defaultZone: http://jnick.xyz:8761/eureka/,http://jnick.xyz:8762/eureka/,http://jnick.xyz:8763/eureka/
management:
  endpoints:
    web:
      expose: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8974
